### PR TITLE
Add More Methods and update TODO List

### PR DESCRIPTION
**Pull request by ghost**
Add UpdateProfileRequest and Account TODO List

### CODE REVIEW

**Comment by steavy29** [comment]
Please, fix to use camel case for fields in request class. `first_name` -> `firstName`

**Comment by TheBottleGit** [comment]
Okay, will be fixed now.

**Comment by TheBottleGit** [comment]
Fixed.

**Comment by TheBottleGit** [comment]
I think that switching to 4.5 will be useful for everyone. Can you please switch it?

**Comment by TheBottleGit** [comment]
Can you write channel constrictors? I will write method for this.

**Comment by munrocket** [comment]
>I think that switching to 4.5 will be useful for everyone

Strange that somebody was thinking like this. CSharp havn't no one .Net Core 1.1-2.0 library for telegram. Your project could be unique in the world. But i guess you reverted it to 4.5 by advice.

**Comment by steavy29** [comment]
At that point of time .net core was just emerging and even no dependencies were available so migrating to lower .net framework version was not a bad idea. Of course, now it makes sense to have it in .net core.
This pr was already closed. Please open new issue if you need something.

**Comment by munrocket** [comment]
I solved my problem thanks! I think it will be beter for your project if you revert it to Core 1.1-2.0.
When somebody found you package with name Telegram.Net.Core in NuGet they expect .Net Core dependencies. Also you know that package Telegram.Net has infinite loop in dependencies?

**Comment by steavy29** [comment]
It's not on nuget. Didn't know it is there. What you see there is some guy's fork of Telegram.Net. It's just not ready to be published.

**Comment by mirror-neuron** [comment]
lul

**Pull request closed without merging**
